services:
  service-registry:
    container_name: service-registry
    image: service-registry
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_INSTANCE_HOSTNAME=service-registry
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8080/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - EUREKA_SERVER_ENABLE_SELF_PRESERVATION=true
      - EUREKA_SERVER_EVICTION_INTERVAL_TIMER_IN_MS=10000
      - EUREKA_SERVER_EXPECTED_CLIENT_RENEWAL_INTERVAL_SECONDS=30
      - EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS=10
      - EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS=30
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/eureka/apps || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - service-registry-network
networks:
  service-registry-network:
    name: service-registry-network
    driver: bridge